package CopaDoMundo.Paises;

import java.util.ArrayList;

public class ListaDePaises 
{
    public ArrayList<String> listaDePaises()
    {
        ArrayList<String> listaPaises = new ArrayList<>();

        listaPaises.add("Afeganistão");
        listaPaises.add("África do Sul");
        listaPaises.add("Albânia");
        listaPaises.add("Alemanha");
        listaPaises.add("Andorra");
        listaPaises.add("Angola");
        listaPaises.add("Antígua e Barbuda");
        listaPaises.add("Arábia Saudita");
        listaPaises.add("Argélia");
        listaPaises.add("Argentina");
        listaPaises.add("Armênia");
        listaPaises.add("Austrália");
        listaPaises.add("Áustria");
        listaPaises.add("Azerbaijão");
        listaPaises.add("Bahamas");
        listaPaises.add("Bahrein");
        listaPaises.add("Bangladesh");
        listaPaises.add("Barbados");
        listaPaises.add("Bélgica");
        listaPaises.add("Belize");
        listaPaises.add("Benin");
        listaPaises.add("Bielorrússia");
        listaPaises.add("Bolívia");
        listaPaises.add("Bósnia e Herzegovina");
        listaPaises.add("Botsuana");
        listaPaises.add("Brasil");
        listaPaises.add("Brunei");
        listaPaises.add("Bulgária");
        listaPaises.add("Burkina Faso");
        listaPaises.add("Burundi");
        listaPaises.add("Butão");
        listaPaises.add("Cabo Verde");
        listaPaises.add("Camboja");
        listaPaises.add("Camarões");
        listaPaises.add("Canadá");
        listaPaises.add("Catar");
        listaPaises.add("Cazaquistão");
        listaPaises.add("Chade");
        listaPaises.add("Chile");
        listaPaises.add("China");
        listaPaises.add("Chipre");
        listaPaises.add("Colômbia");
        listaPaises.add("Comores");
        listaPaises.add("Congo");
        listaPaises.add("Coreia do Norte");
        listaPaises.add("Coreia do Sul");
        listaPaises.add("Costa do Marfim");
        listaPaises.add("Costa Rica");
        listaPaises.add("Croácia");
        listaPaises.add("Cuba");
        listaPaises.add("Dinamarca");
        listaPaises.add("Djibouti");
        listaPaises.add("Dominica");
        listaPaises.add("Egito");
        listaPaises.add("El Salvador");
        listaPaises.add("Emirados Árabes Unidos");
        listaPaises.add("Equador");
        listaPaises.add("Eritreia");
        listaPaises.add("Eslováquia");
        listaPaises.add("Eslovênia");
        listaPaises.add("Espanha");
        listaPaises.add("Estados Unidos");
        listaPaises.add("Estônia");
        listaPaises.add("Eswatini");
        listaPaises.add("Etiópia");
        listaPaises.add("Fiji");
        listaPaises.add("Filipinas");
        listaPaises.add("Finlândia");
        listaPaises.add("França");
        listaPaises.add("Gabão");
        listaPaises.add("Gâmbia");
        listaPaises.add("Gana");
        listaPaises.add("Geórgia");
        listaPaises.add("Granada");
        listaPaises.add("Grécia");
        listaPaises.add("Guatemala");
        listaPaises.add("Guiana");
        listaPaises.add("Guiné");
        listaPaises.add("Guiné Equatorial");
        listaPaises.add("Guiné-Bissau");
        listaPaises.add("Haiti");
        listaPaises.add("Holanda");
        listaPaises.add("Honduras");
        listaPaises.add("Hungria");
        listaPaises.add("Iêmen");
        listaPaises.add("Ilhas Marshall");
        listaPaises.add("Ilhas Salomão");
        listaPaises.add("Índia");
        listaPaises.add("Indonésia");
        listaPaises.add("Irã");
        listaPaises.add("Iraque");
        listaPaises.add("Irlanda");
        listaPaises.add("Islândia");
        listaPaises.add("Israel");
        listaPaises.add("Itália");
        listaPaises.add("Jamaica");
        listaPaises.add("Japão");
        listaPaises.add("Jordânia");
        listaPaises.add("Kiribati");
        listaPaises.add("Kuwait");
        listaPaises.add("Laos");
        listaPaises.add("Lesoto");
        listaPaises.add("Letônia");
        listaPaises.add("Líbano");
        listaPaises.add("Libéria");
        listaPaises.add("Líbia");
        listaPaises.add("Liechtenstein");
        listaPaises.add("Lituânia");
        listaPaises.add("Luxemburgo");
        listaPaises.add("Macedônia do Norte");
        listaPaises.add("Madagascar");
        listaPaises.add("Malásia");
        listaPaises.add("Malawi");
        listaPaises.add("Maldivas");
        listaPaises.add("Mali");
        listaPaises.add("Malta");
        listaPaises.add("Marrocos");
        listaPaises.add("Maurício");
        listaPaises.add("Mauritânia");
        listaPaises.add("México");
        listaPaises.add("Micronésia");
        listaPaises.add("Moçambique");
        listaPaises.add("Moldávia");
        listaPaises.add("Mônaco");
        listaPaises.add("Mongólia");
        listaPaises.add("Montenegro");
        listaPaises.add("Myanmar");
        listaPaises.add("Namíbia");
        listaPaises.add("Nauru");
        listaPaises.add("Nepal");
        listaPaises.add("Nicarágua");
        listaPaises.add("Níger");
        listaPaises.add("Nigéria");
        listaPaises.add("Noruega");
        listaPaises.add("Nova Zelândia");
        listaPaises.add("Omã");
        listaPaises.add("Palau");
        listaPaises.add("Panamá");
        listaPaises.add("Papua Nova Guiné");
        listaPaises.add("Paquistão");
        listaPaises.add("Paraguai");
        listaPaises.add("Peru");
        listaPaises.add("Polônia");
        listaPaises.add("Portugal");
        listaPaises.add("Quênia");
        listaPaises.add("Quirguistão");
        listaPaises.add("Quiribati");
        listaPaises.add("Reino Unido");
        listaPaises.add("República Centro-Africana");
        listaPaises.add("República Dominicana");
        listaPaises.add("República Tcheca");
        listaPaises.add("Romênia");
        listaPaises.add("Ruanda");
        listaPaises.add("Rússia");
        listaPaises.add("Samoa");
        listaPaises.add("San Marino");
        listaPaises.add("Santa Lúcia");
        listaPaises.add("São Cristóvão e Nevis");
        listaPaises.add("São Tomé e Príncipe");
        listaPaises.add("São Vicente e Granadinas");
        listaPaises.add("Senegal");
        listaPaises.add("Sérvia");
        listaPaises.add("Seychelles");
        listaPaises.add("Serra Leoa");
        listaPaises.add("Singapura");
        listaPaises.add("Síria");
        listaPaises.add("Somália");
        listaPaises.add("Sri Lanka");
        listaPaises.add("Suazilândia");
        listaPaises.add("Sudão");
        listaPaises.add("Sudão do Sul");
        listaPaises.add("Suécia");
        listaPaises.add("Suíça");
        listaPaises.add("Suriname");
        listaPaises.add("Tailândia");
        listaPaises.add("Taiwan");
        listaPaises.add("Tajiquistão");
        listaPaises.add("Tanzânia");
        listaPaises.add("Timor-Leste");
        listaPaises.add("Togo");
        listaPaises.add("Tonga");
        listaPaises.add("Trinidad e Tobago");
        listaPaises.add("Tunísia");
        listaPaises.add("Turcomenistão");
        listaPaises.add("Turquia");
        listaPaises.add("Tuvalu");
        listaPaises.add("Ucrânia");
        listaPaises.add("Uganda");
        listaPaises.add("Uruguai");
        listaPaises.add("Uzbequistão");
        listaPaises.add("Vanuatu");
        listaPaises.add("Vaticano");
        listaPaises.add("Venezuela");
        listaPaises.add("Vietnã");
        listaPaises.add("Zâmbia");
        listaPaises.add("Zimbábue");

        return listaPaises;
    }
    
}
