package CopaDoMundo.Paises;

import java.util.ArrayList;

public class ListaDeJogadores 
{
    public ArrayList<String> listaDeJogadoresArrayList()
    {
        ArrayList<String> jogadores = new ArrayList<>();

        jogadores.add("Lionel Messi");
        jogadores.add("Cristiano Ronaldo");
        jogadores.add("Neymar Jr.");
        jogadores.add("Kylian Mbappé");
        jogadores.add("Robert Lewandowski");
        jogadores.add("Kevin De Bruyne");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Mohamed Salah");
        jogadores.add("Sergio Ramos");
        jogadores.add("Luka Modrić");
        jogadores.add("Harry Kane");
        jogadores.add("Manuel Neuer");
        jogadores.add("Sadio Mané");
        jogadores.add("Antoine Griezmann");
        jogadores.add("Eden Hazard");
        jogadores.add("Paul Pogba");
        jogadores.add("Gareth Bale");
        jogadores.add("Luis Suárez");
        jogadores.add("Edinson Cavani");
        jogadores.add("Thiago Alcântara");
        jogadores.add("Karim Benzema");
        jogadores.add("Toni Kroos");
        jogadores.add("Sergio Agüero");
        jogadores.add("Sergio Busquets");
        jogadores.add("Andrés Iniesta");
        jogadores.add("David Silva");
        jogadores.add("Zlatan Ibrahimović");
        jogadores.add("Sergio Oliveira");
        jogadores.add("Bruno Fernandes");
        jogadores.add("Diogo Jota");
        jogadores.add("João Félix");
        jogadores.add("Bernardo Silva");
        jogadores.add("Ciro Immobile");
        jogadores.add("Romelu Lukaku");
        jogadores.add("Raheem Sterling");
        jogadores.add("David Alaba");
        jogadores.add("Marc-André ter Stegen");
        jogadores.add("N'Golo Kanté");
        jogadores.add("Marco Verratti");
        jogadores.add("Jadon Sancho");
        jogadores.add("Joshua Kimmich");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Alisson Becker");
        jogadores.add("Thibaut Courtois");
        jogadores.add("Jamie Vardy");
        jogadores.add("Pierre-Emerick Aubameyang");
        jogadores.add("Christian Pulisic");
        jogadores.add("Hakim Ziyech");
        jogadores.add("Heung-min Son");
        jogadores.add("Thomas Müller");
        jogadores.add("Frenkie de Jong");
        jogadores.add("Georginio Wijnaldum");
        jogadores.add("Memphis Depay");
        jogadores.add("Lorenzo Insigne");
        jogadores.add("Miralem Pjanić");
        jogadores.add("Kai Havertz");
        jogadores.add("Ángel Di María");
        jogadores.add("César Azpilicueta");
        jogadores.add("Ederson");
        jogadores.add("Riyad Mahrez");
        jogadores.add("Alexandre Lacazette");
        jogadores.add("Gabriel Jesus");
        jogadores.add("Vinícius Júnior");
        jogadores.add("Lucas Moura");
        jogadores.add("Rodrygo");
        jogadores.add("Federico Valverde");
        jogadores.add("Isco");
        jogadores.add("Timo Werner");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Jan Oblak");
        jogadores.add("Dries Mertens");
        jogadores.add("Giovani Lo Celso");
        jogadores.add("James Rodríguez");
        jogadores.add("Leroy Sané");
        jogadores.add("Kingsley Coman");
        jogadores.add("Nabil Fekir");
        jogadores.add("Alejandro Gómez");
        jogadores.add("Keylor Navas");
        jogadores.add("Nemanja Matić");
        jogadores.add("Luka Jović");
        jogadores.add("Andrea Belotti");
        jogadores.add("Marquinhos");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Lucas Paquetá");
        jogadores.add("Philippe Coutinho");
        jogadores.add("Ivan Rakitić");
        jogadores.add("Paulo Dybala");
        jogadores.add("Gonzalo Higuaín");
        jogadores.add("Hirving Lozano");
        jogadores.add("Hugo Lloris");
        jogadores.add("Ciro Immobile");
        jogadores.add("Nicolas Pépé");
        jogadores.add("Luka Dončić");
        jogadores.add("Zinedine Zidane");
        jogadores.add("Xavi Hernández");
        jogadores.add("Andrea Pirlo");
        jogadores.add("Ronaldo Nazário");
        jogadores.add("Ronaldinho Gaúcho");
        jogadores.add("Fernando Torres");
        jogadores.add("Steven Gerrard");
        jogadores.add("Frank Lampard");
        jogadores.add("Andriy Shevchenko");
        jogadores.add("Patrick Vieira");
        jogadores.add("Roy Keane");
        jogadores.add("Thierry Henry");
        jogadores.add("Ryan Giggs");
        jogadores.add("Paolo Maldini");
        jogadores.add("Andrea Barzagli");
        jogadores.add("Alessandro Nesta");
        jogadores.add("Roberto Carlos");
        jogadores.add("Cafu");
        jogadores.add("Fábio Cannavaro");
        jogadores.add("Marco Materazzi");
        jogadores.add("Carles Puyol");
        jogadores.add("Raphaël Varane");
        jogadores.add("Sami Khedira");
        jogadores.add("David Trezeguet");
        jogadores.add("Zlatan Ibrahimović");
        jogadores.add("Edgar Davids");
        jogadores.add("Gennaro Gattuso");
        jogadores.add("Pavel Nedvěd");
        jogadores.add("Michael Ballack");
        jogadores.add("Deco");
        jogadores.add("Rui Costa");
        jogadores.add("Hernán Crespo");
        jogadores.add("Alessandro Del Piero");
        jogadores.add("Gianluigi Buffon");
        jogadores.add("Oliver Kahn");
        jogadores.add("Iker Casillas");
        jogadores.add("Edwin van der Sar");
        jogadores.add("Marc-André ter Stegen");
        jogadores.add("Manuel Neuer");
        jogadores.add("Alisson Becker");
        jogadores.add("Keylor Navas");
        jogadores.add("David de Gea");
        jogadores.add("Jan Oblak");
        jogadores.add("Thibaut Courtois");
        jogadores.add("Hugo Lloris");
        jogadores.add("Jasper Cillessen");
        jogadores.add("Bernd Leno");
        jogadores.add("Samir Handanović");
        jogadores.add("Wojciech Szczęsny");
        jogadores.add("Gianluigi Donnarumma");
        jogadores.add("Kepa Arrizabalaga");
        jogadores.add("Rui Patrício");
        jogadores.add("Ralf Fährmann");
        jogadores.add("Alexander-Arnold");
        jogadores.add("João Cancelo");
        jogadores.add("Joshua Kimmich");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kieran Trippier");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Sergio Reguilón");
        jogadores.add("Jordi Alba");
        jogadores.add("Lucas Hernández");
        jogadores.add("Andrew Robertson");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");
        jogadores.add("Kalidou Koulibaly");
        jogadores.add("Raphaël Varane");
        jogadores.add("Milan Škriniar");
        jogadores.add("Leonardo Bonucci");
        jogadores.add("Aymeric Laporte");
        jogadores.add("Niklas Süle");
        jogadores.add("Matthijs de Ligt");
        jogadores.add("Marquinhos");
        jogadores.add("Gerard Piqué");
        jogadores.add("Kostas Manolas");
        jogadores.add("Dayot Upamecano");
        jogadores.add("Harry Maguire");
        jogadores.add("Jose Gimenez");
        jogadores.add("Samuel Umtiti");
        jogadores.add("Presnel Kimpembe");
        jogadores.add("Eder Militão");
        jogadores.add("Victor Lindelöf");
        jogadores.add("Andreas Christensen");
        jogadores.add("Nico Elvedi");
        jogadores.add("Caglar Soyuncu");
        jogadores.add("Jonathan Tah");
        jogadores.add("Davinson Sánchez");
        jogadores.add("Jason Denayer");
        jogadores.add("Ibrahima Konaté");
        jogadores.add("Diego Godín");
        jogadores.add("Pepe");
        jogadores.add("Giorgio Chiellini");
        jogadores.add("Stefan de Vrij");
        jogadores.add("José María Giménez");
        jogadores.add("Diego Carlos");
        jogadores.add("Eric Bailly");
        jogadores.add("John Stones");
        jogadores.add("Ethan Ampadu");
        jogadores.add("Merih Demiral");
        jogadores.add("Edmond Tapsoba");
        jogadores.add("Marcos Senesi");
        jogadores.add("Kristoffer Ajer");
        jogadores.add("Jules Koundé");
        jogadores.add("Ozan Kabak");
        jogadores.add("Pau Torres");
        jogadores.add("Ruben Dias");
        jogadores.add("Reece James");
        jogadores.add("Trent Alexander-Arnold");
        jogadores.add("Achraf Hakimi");
        jogadores.add("Aaron Wan-Bissaka");
        jogadores.add("Ricardo Pereira");
        jogadores.add("Jesus Navas");
        jogadores.add("Dani Carvajal");
        jogadores.add("Nélson Semedo");
        jogadores.add("Kyle Walker");
        jogadores.add("Hakimi");
        jogadores.add("Benjamin Pavard");
        jogadores.add("Nico Schulz");
        jogadores.add("Ferland Mendy");
        jogadores.add("Alex Telles");
        jogadores.add("Lucas Digne");
        jogadores.add("Andrew Robertson");
        jogadores.add("Lucas Hernández");
        jogadores.add("Marcelo");
        jogadores.add("Alex Sandro");
        jogadores.add("Grimaldo");
        jogadores.add("Juan Bernat");
        jogadores.add("Álex Grimaldo");
        jogadores.add("Jordi Alba");
        jogadores.add("Filipe Luís");
        jogadores.add("Luke Shaw");
        jogadores.add("David Alaba");
        jogadores.add("Layvin Kurzawa");
        jogadores.add("Sergio Ramos");
        jogadores.add("Virgil van Dijk");

        return jogadores;
    }
}
